### ISSUE TITLE
More Info

### ISSUE THREAD

**Issue by ynx0** [shiv213/Artificial-Intelligence-for-Colon-Cancer-Detection#1]
The code looks good, but a better explanation of the code would be helpful.
Thank you very much sir for the time it took you to write this.

**Comment by shiv213** [comment]
Oh well maybe I'll do that then, thank you!
Thank you very much sir for the time it took you to write this comment.

**Comment by ynx0** [comment]
No problem sir.
Thank you very much for considering it.
